### ISSUE TITLE
RS 001: Tipo de pokemon

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#15]
- Descripcion: Los Pokemon necesitan un atributo llamado Tipo, el cual afecta la fortaleza de sus ataques, y la resistencia de ataques enemigos. Se necesita implementar lo anterior.
- Fuente: Juaquin Torres, Sergio.
- Prioridad: Critica.
- Estabilidad: Intransable.
- Fecha Actualizacion: 26/10/2016
- Estado: Cumple.
- Incremento: 1.
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicación.

Requisitos de Usuario asociados:
1. [RU 001: Debilidad ataques](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-001-debilidad-ataques)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by Afromatico** [comment]
**Initialization:** 
Cada Pokemon tiene su tipo asociado.

**Comment by Afromatico** [comment]
**Concept Location:**
friends, monster, bosses

**Comment by Afromatico** [comment]
**Impact Analysis:**
- Friend
- AbstractFriend

**Comment by Afromatico** [comment]
**Prefactoring**:
Se creo una nuevo package, se creo una interface IType, una clase abstracta Abstract Type, y se crearon todas las posibles clases para Typos conocidos de pokemon.

**Comment by Afromatico** [comment]
**Changue Propagation:**
Se asigno Array de Tipos para cada friend, esto no afecto directamente a otras clases.

**Comment by Afromatico** [comment]
**Verification:**
Funciona la implementación, cada pokemon se le puede asignar los tipos necesarios, se puede editar libremente, luego no necesita postfactoring.

**Comment by Afromatico** [comment]
**Conclusion:**
Se agregaron los tipos de cada pokemon.

**Comment by gsanhueza** [comment]
Memory leak al jugar, reabriendo issue

**Comment by gsanhueza** [comment]
EDIT: Error de issue, cerrando
