### ISSUE TITLE
RS 002: Agregar tipo de cada ataque

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#16]
- Descripción: Agregar tipo asociado a cada ataque, ese trabaja en conjunto con el Tipo del pokemon para determinar su eficacia.
- Fuente: Joaquin Torres, Sergio.
- Prioridad: Critica.
- Estabilidad: Intransable.
- Fecha Actualización: 26/10/2016
- Estado: Cumple.
- Incremento: 1.
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicación.

Requisitos de Usuario asociados:
1. [RU 001: Debilidad ataques](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-001-debilidad-ataques)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by Afromatico** [comment]
**Initialization:** 
Cada ataque tiene un tipo asociado.

**Comment by Afromatico** [comment]
**Concept Location:**
SpriteState, attacks

**Comment by Afromatico** [comment]
**Impact Analysis:**
-  Todas las clases del paquete attacks.state
-  Todas las clases del paquete attacks

**Comment by Afromatico** [comment]
**Prefactoring**:
Se utilizo el paquete creado en #15 y se asigno un topo a cada Clase en atacks.state, ademas de un getter y un setter.

**Comment by Afromatico** [comment]
**Changue Propagation:**
Se asigno el tipo de cada Sprite, no afecto directamente a otras clases.

**Comment by Afromatico** [comment]
**Verification:**
Funciona la implementación, a cada ataque se le puede asignar los tipos necesarios, se puede editar libremente, luego no necesita postfactoring.

**Comment by Afromatico** [comment]
**Conclusion:**
Se agregaron los tipos de cada ataque.
