### ISSUE TITLE
RS 003: Formula de daño

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#17]
- Descripción: Cambiar formula de daño para que varíe con el tipo del ataque y pokemon.
- Fuente: Juaquin Torres, Sergio.
- Prioridad: Critica.
- Estabilidad: Intransable.
- Fecha Actualizacion: 26/10/2016
- Estado: Cumple.
- Incremento: 1.
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicación.

Requistitos de Usuario asociados:
1. [RU 001: Debilidad ataques](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-001-debilidad-ataques)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by martinpanza** [comment]
### Concept Location

Formula, Damage, Attack Type, Pokemon Type

**Comment by Afromatico** [comment]
**Initialization:** 
Se requiere modificar a formula de daño integrando el tipo de pokemon y el tipo del ataque.

**Comment by Afromatico** [comment]
**Concept Location:**
Formula, Damage, Attack Type, Pokemon Type
@martinpanza

**Comment by Afromatico** [comment]
**Impact Analysis:**

Todas las clases de los sigueintes paquetes:
- actors.attacks
- actors.attacks.states
- actors.actors.bosses
- actors.actors.enemies
- actors.actors.friend
- types
- Clase Formulas

**Comment by Afromatico** [comment]
**Prefactoring**:
Se cambio la clase abstracta attacks, donde se entregan las referencias a los tipos del pokemon atacante, el tipo del pokemon atacado y el tipo del ataque como parámetros de la formula. En la formula se agregaron los efectos de las interacciones entre estas nuevas variables.

**Comment by Afromatico** [comment]
**Changue Propagation:**
Se asigno el la eficacia de cada tipo de daño en el tipo de los pokemon, eso no afecto a otras clases.

**Comment by Afromatico** [comment]
**Verification:**
Funciona la complementación, en el juego ahora funciona la variación de daño dependiendo del tipo de pokemon, del tipo del ataque y del tipo del pokemon afectado.

**Comment by Afromatico** [comment]
**Conclusion:**
El daño fue modificado y es coherente con lo esperado.
