### ISSUE TITLE
RS 004: Stats bases nuevos

### ISSUE THREAD

**Issue by Afromatico** [belisariops/ATK#18]
- Descripcion: Asignar valores base para cada tipo de nueva criatura.
- Fuente:
- Prioridad:
- Estabilidad:
- Fecha Actualizacion:
- Estado:
- Incremento:
- Tipo:
- Usuario Asociado:

Requistitos de Usuario asociados:
1. [RU 002:Nuevos ataques y personajes](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-002-nuevos-ataques-y-personajes)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by jaevespinoza** [comment]
**Initialization**
Se deben agregar los stats ´de los pokemon nuevos al juego

**Comment by jaevespinoza** [comment]
**Concept Location**
Stats, New Pokemon, agregar

**Comment by jaevespinoza** [comment]
**Impact Analysis**
Todo el paquete actors.actors.enemies y actors.actors.friend.

**Comment by jaevespinoza** [comment]
**Pre-factoring**
Se comenzaron a definir las variables en la enumeración Enemies dentro del paquete actors.actors.friend.
Este contiene los stats de cada pokemon presente en el juego.

**Comment by jaevespinoza** [comment]
**Change Propagation**
Se añadieron todos los stats correspondientes a los pokemon a añadir. Solamente fue afectada la clase Enemies.java.

**Comment by jaevespinoza** [comment]
**Verification**
Los stats correspondientes a cada pokemon son correctos

**Comment by jaevespinoza** [comment]
**Postfactoring**

Se añadió cada stat a la clase del pokemon correspondiente

**Comment by jaevespinoza** [comment]
**Conclusion**

Los stats fueron implementados correctamente.
