### ISSUE TITLE
RS 005: Nuevos Pokemones

### ISSUE THREAD

**Issue by Afromatico** [belisariops/ATK#19]
- Descripcion: Agregar nuevos personajes al juego para que el jugador pueda utilizarlos.
- Fuente: Cliente
- Prioridad: Critica
- Estabilidad: Intransable
- Fecha Actualizacion: 06-12-2016
- Estado: Cumple
- Incremento: 3
- Tipo: Funcional
- Usuario Asociado: Jugador

Requistitos de Usuario asociados:
1. [RU 001: Debilidad ataques](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-001-debilidad-ataques)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by jaevespinoza** [comment]
**Initialization**
Se deben agregar nuevos pokemon al juego.

**Comment by jaevespinoza** [comment]
**Concept Location**
Nuevo Pokemon, Juego, Agregar

**Comment by jaevespinoza** [comment]
**Impact Analysis**
El paquete friends debe ser afectado, pues se están agregando clases a éste.

**Comment by jaevespinoza** [comment]
**Prefactoring**
Se comienzan a agregar clases para 7 lineas de evolución Pokemon. Estas clases todavia no poseen las texturas necesarias para poder ser mostradas en el juego.

**Comment by jaevespinoza** [comment]
**Change Propagation:**

Se modificaron las clases:
MonsterFactory
Enemies
ChooseStage

**Comment by jaevespinoza** [comment]
**Verification**

Se agregaron los pokemon necesarios

**Comment by jaevespinoza** [comment]
**Post factoring**

Arreglar setCutSprites para que cada sprite pueda caber.

**Comment by jaevespinoza** [comment]
**Conclusión**

Pokemon agregados al juego
