### ISSUE TITLE
RS 008: Clima

### ISSUE THREAD

**Issue by jaevespinoza** [belisariops/ATK#22]
- Descripcion: Implementar y crear los efectos de clima en el juego
- Fuente:
- Prioridad: Critica
- Estabilidad: Intransable
- Fecha Actualizacion: 27/10/2016 18:00
- Incremento: 0
- Tipo: Funcional

Requistitos de Usuario asociados:
1. RU004: Clima
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

Dentro del paquete debe haber una interfaz IClimate, una clase abstracta AbstractClimate, y luego las variaciones de clima que uno quiere (HailClimate, RainClimate, SunnyClimate, NormalClimate, SandClimate, etc)

**Comment by AnnBenavides** [comment]
se discutió el funcionamiento de este elemento de la siguiente manera:
- Cada Stage tendrá un Clima
- Al entrar al Stage el Hero le entregará a clima su arreglo con Friends a los que se les modificará los EVs según coresponda

_Por ver: Modificar stats de friend atrapado en el stage actual, se propone que se agregue un listener a Hero en caso de atrapar un nuevo friend, recalcular los stats del equipo completo_

**Comment by AnnBenavides** [comment]
Postfactoring:

-[RS041: Animaciones para Clima](https://github.com/belisariops/ATK/issues/113)
