### ISSUE TITLE
RS 009: PC

### ISSUE THREAD

**Issue by Afromatico** [belisariops/ATK#23]
- Descripcion: Implementar un almacenamiento y sistema de intercambio de pokemon, entre un grupo guardado en el PokemonComputer y  los cuatro pokemon del equipo que se tiene al estar jugando. 
- Fuente: Joaquin Torres, Sergio Peñafiel.
- Prioridad: Critica
- Estabilidad: Intransable
- Fecha Actualizacion: 04/12/2016
- Estado: Cumple.
- Incremento: 1
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicacion.

Requistitos de Usuario asociados:
1. [RU 003: Crear almacenamiento personajes](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-003-crear-almacenamiento-personajes)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by Benrodf** [comment]
**Initialization:**
Crear pantalla de intercambio (llamada PC) entre los Pokemon del equipo de cuatro y el resto.

**Comment by Benrodf** [comment]
**Concept Location:**
friend, allies, backupAllies, changeAllies, screen.

**Comment by Benrodf** [comment]
**Impact Analysis:**
- Friend
- Hero
- Enemy
- SimpleScreen
- GameScreen
- MapScreen
- PokeCenterScreen
- MenuScreen

**Comment by Benrodf** [comment]
**Prefactoring:**
Se creó una nueva clase PokeComputerScreen, lugar donde se realizan los intercambios de Pokemon a través del uso de indices en los arreglos del equipo y la reserva en el PC. El proceso de cambio de posicion es  gatillando al apretar el boton Swap.

**Comment by Benrodf** [comment]
**Change Propagation:**
Se modificó MapSCreen para que PokeComputerScreen sea accesible durante la seleccion de etapas en el mapa, y se creó el metodo swapTeamAllies en la clase Hero, el cual es ejecutado al pulsar el boton Swap en el PokeComputer. El resto de las clases se mantuvieron intactas.

**Comment by Benrodf** [comment]
**Verification:**
Funciona la implementacion, se intercambian Pokemon entre los 4 disponibles para utilizar durante el juego (team Pokemon) y el grupo de los Pokemon extra capturados (backup Pokemon). Los indices del intercambio se manejan a través de 2 botones para los team Pokemon y con 4 botones para los backup Pokemon, dentro de los cuales dos son para el cambio de página en la pantalla (debido a que los Pokemon atrapados no caben todos en el mismo lugar). Este sistema puede ser modificado para mejorar la calidad de la interfaz de usuario.

**Comment by Benrodf** [comment]
**Conclusion:**
Se creó un sistema de almacenamiento e intercambio entre los 4 Pokemon del equipo disponible para jugar y el resto de los Pokemon atrapados.
