### ISSUE TITLE
RS 010: Bugs Pokebola

### ISSUE THREAD

**Issue by Benrodf** [belisariops/ATK#24]
- Descripción: Ocasionalmente, al atrapar un pokemon y desaparecer, el colider de la entidad sigue existiendo (de forma invisible), haciendo imposible atravesar con tu personaje por ese sector. Por otro lado, mientras se está en el proceso de atrapar un pokemon (cuando la pokebola se balancea), una "versión invisible del pokemon" sigue la trayectoria que éste llevaba antes de ser atrapado y continúa realizando ataques (los cuales si son visibles).
- Fuente: Nuestro equipo
- Prioridad: Crítica
- Estabilidad: Intransable
- Fecha Actualizacion: 2/11/2016
- Estado: Cumple
- Incremento: 1
- Tipo: Calidad
- Usuario Asociado: Usuario de la aplicación

- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by martinpanza** [comment]
### Inicialization

Bug al lanzar Pokebola al enemigo.

**Comment by martinpanza** [comment]
### Concept Location

-Pokeball
-Enemy

**Comment by martinpanza** [comment]
### Impact Analysis

Clases que podrían verse afectadas:

-Enemy
-Hero
-Friend
-World
-GameActor
-EnemyCreator
-FLyWaveAndDropEnemy
-FollowerEnemy
-JumperEnemy
-LongRangeEnemy
-PhysicalEnemy
-StayAndShootEnemy
-Platform
-Ball
-BallActor
-Inventory
-Attacks
-MonsterFactory

**Comment by martinpanza** [comment]
### Prefactoring

Se utiliza el atributo existente 'free' del enemigo para evitar al pokemon realizar ataques mientras este sea false. Por otro lado, en caso de cumplir con los requisitos de captura, se elimina al enemigo del juego al comenzar la interacción con la pokebola. En caso contrario, se desactiva el 'body' del enemigo durante la interacción. Finalmente, se desactiva el 'body' de la pokebola al interactuar con un enemigo.

**Comment by martinpanza** [comment]
### Change Propagation

Clases impactadas:
-Enemy
-FlyWaveAndDropEnemy
-FollowerEnemy
-JumperEnemy
-StayAndShootEnemy
-BallActor

**Comment by martinpanza** [comment]
### Verification

Se verificó utilizando todas las pokebolas posibles y se confirmó la ausencia del collider junto con los ataques . No requiere postfactoring.

**Comment by martinpanza** [comment]
### Conclusion

Bug arreglado, los pokemones son capturados de la forma esperada.
