### ISSUE TITLE
RS 011: Implementar PC en Hero

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#25]
- Descripcion: Implementar un sistema de almacenamiento para los Pokemon en caso de tener los cuatro cupos del equipo jugable llenos, dentro de la clase Hero, para su posterior utilización en el PokeComputer (PC). 
- Fuente: Joaquin Torres, Sergio Peñafiel.
- Prioridad: Critica
- Estabilidad: Intransable
- Fecha Actualizacion: 03/11/2016
- Estado: Cumple.
- Incremento: 1
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicacion.

Requistitos de Usuario asociados:
1. [RU 003: Crear almacenamiento personajes](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-003-crear-almacenamiento-personajes)

- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by Benrodf** [comment]
**Initialization:**
Almacentamiento de más de cuatro Pokemon atrapados en clase Hero.

**Comment by Benrodf** [comment]
**Concept Location:**
save, friend, allies, addAllies.

**Comment by Benrodf** [comment]
**Impact Analysis:**
- Hero
- Friend
- Enemys
- BallActor
- SaveManager

**Comment by Benrodf** [comment]
**Prefactoring:**
Se crea un arreglo de Friends similar a allies llamado backupAllies, allí son guardados los Pokemon por el metodo addAllies en caso de que el largo de allies sea cuatro. El metodo saveMyFriends ahora incluye a los elementos de backupAllies en el arreglo friends retornado, de manera que se guardan permanentemente.

**Comment by Benrodf** [comment]
**Change Propagation:**
Solo se modificaron metodos y crearon arreglos en la clase Hero, esto no afectó directamente a otras clases.

**Comment by Benrodf** [comment]
**Verification:**
Funciona la implementacion, se maneja y guarda encapsuladamente los atributos de cada Pokemon capturado, ya sea en allies o en backupAllies, lo que permitirá su posterior utilización en el sistema de intercambio PokeComputer (PC), luego no necesita postfactoring.

**Comment by Benrodf** [comment]
**Conclusion:**
Se creó almacenamiento para un conjunto mayor a cuatro Pokemon en clase Hero.
