### ISSUE TITLE
RS 012: Botones pantalla principal

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#26]
- Descripcion:  Agregar dos botones, uno que carge un juego anterior y otro que agregue un nuevo juego
- Fuente: Juaquin Torres, Sergio.
- Prioridad: Critica.
- Estabilidad: Intransable.
- Fecha Actualizacion: 25/10/2016
- Estado: Cumple.
- Incremento: 0.
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicacion..

Requistitos de Usuario asociados:
1. [RU 010: Agregar botones "New Game" y "Load Game"](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-010-agregar-botones-new-game-y-load-game)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by chantezan** [comment]
Initialization: Se necesita el boton new game que cree un juego automaticamente y que el boton load game solo cargue juegos

**Comment by chantezan** [comment]
concept location: new game, LoadGame

**Comment by chantezan** [comment]
impact analisis: MenuScreen,LoadStage

**Comment by chantezan** [comment]
prefactoring: Se modifico la clase loadStage para que solamente cargue los juegos creados, y la clase MenuScreen para que al apretar el boton newGame se cree un juego automaticamente y se guarde.

**Comment by chantezan** [comment]
Change Propagation: LoadStage, MenuScreen

**Comment by chantezan** [comment]
verification: ambos botones se comportan correctamente y realizan las funciones solicitadas

**Comment by chantezan** [comment]
conclusion: una mejora verificada al juego
