### ISSUE TITLE
RS 013: Crear menu de opciones

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#27]
- Descripción: El botón de opciones no tiene utilidad, por lo que se pide agregar opciones para modificar brillo, volumen y estado de la ventana.
- Fuente: Joaquin Torres.
- Prioridad: Crítica.
- Estabilidad: Intransable.
- Fecha Actualización: 10/11/2016 17:51:00.
- Incremento: 1.
- Tipo: Funcional.

Requisitos de Usuario asociados:
1. [RU 013: Implementar opciones](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-013-implementar-opciones)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by gsanhueza** [comment]
**Initialization**

Implementar menú de opciones

**Comment by gsanhueza** [comment]
**Concept Location**

Options, Menu, Screen, Music

**Comment by gsanhueza** [comment]
**Impact Analysis**

Clases que se podrían ver impactadas:
- SimpleScreen
- MenuScreen
- AbstractStage

**Comment by gsanhueza** [comment]
**Prefactoring**

En la clase AbstractStage hay un objeto Music, la cual reproduce todas las canciones necesarias en el juego. En MenuStage está el botón de acceso a Options, pero no hay un OptionsStage, por lo que se crea uno, donde se guardan de forma estática los distintos valores de volumen, brillo y estado de la ventana.

**Comment by gsanhueza** [comment]
**Change Propagation**

Las 3 clases del Impact Analysis fueron impactadas.

**Comment by gsanhueza** [comment]
**Verification**

El brillo funciona correctamente y el volumen se cambia para todas las Stages.

**Comment by gsanhueza** [comment]
**Postfactoring**

Se encontró un Memory Leak, porque se creaban muchos objetos por segundo, que solo se usaban una vez. Se cambió new ShapeRenderer desde "render" hacia la declaración inicial, para crearlo solo una vez.

Incremento 1:

Se creó una clase común GDXSoundEffectsPlayer. Se modificaron los _stages_ que usaban las clases GDXSoundEffects{Hero, Enemy} (MiniGameStage, AbstractStage, BossStage, GameStage, MapStage, MenuStage). Se implementó un nuevo slider en OptionsStage para controlar el sonido de los efectos especiales. Se modificaron las clases Hero y Enemy para usar el sistema refactorizado de sonido.

**Comment by gsanhueza** [comment]
**Conclusion**

El menú de opciones está implementado y es funcional respecto a todo el juego.

Incremento 1:

Se implementó la opción de modificar el sonido de los efectos especiales.
