### ISSUE TITLE
RS 014: Menu cargar juego

### ISSUE THREAD

**Issue by Afromatico** [belisariops/ATK#28]
- Descripcion: En la version actual solo se puden cargar dos juegos antiguos, ahora se quiere cargar N partidas.
- Fuente: Juaquin Torres, Sergio.
- Prioridad: Critica.
- Estabilidad: Intransable.
- Fecha Actualizacion: 25/10/2016
- Estado: Cumple.
- Incremento: 0.
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicacion..

Requistitos de Usuario asociados:
1. [RU 010: Agregar botones "New Game" y "Load Game"](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-010-agregar-botones-new-game-y-load-game)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by chantezan** [comment]
initialization: se necesita que se puedan guardar N juegos

**Comment by chantezan** [comment]
concep location: LoadStage

**Comment by chantezan** [comment]
impact analisis: LoadStage

**Comment by chantezan** [comment]
prefactoring: Primero se modifico la forma en que se guardan los juegos, si el ultimo archivo es ATK6.sav el proximo juego guardado se llamara ATK7.sav ambos guardados en la carpeta Save, con esto ya se pueden guardar N juegos, en la clase LoadStage al iniciar se cargan todos los archivos .sav, guarda los titulos en un array. para seleccionar los juegos cada vez que la flecha se mueve se cargan los juegos dependiendo de la nueva posicion de la flecha, tambien se cargan los listener de los click, tambien un indicador que indica a que juego esta apuntando la flecha para saber que juego cargar.

**Comment by chantezan** [comment]
change propagation: LoadStage, Actor.

**Comment by chantezan** [comment]
verification: se guardan N juegos y es posible poder cargar cuaquiera de esos N juegos

**Comment by chantezan** [comment]
conclusion: la issue esta cerrada y no hay ningun problema en la cargada de juegos ni tampoco al crear un nuevo juego.
