### ISSUE TITLE
RS 018: Nueva mecanica de ataque

### ISSUE THREAD

**Issue by Afromatico** [belisariops/ATK#33]
- Descripcion: En estos momentos se necesitan de dos botones para los asatque, debido a que este juego puede ser usado en el celular se necesita decrecer la cantidad de botones, por lo que los ataques del personaje podriabn hacerce apretando rapidamente el boton o manteniendolo apretado.
- Fuente:
- Prioridad:
- Estabilidad:
- Fecha Actualizacion:
- Estado:
- Incremento:
- Tipo:
- Usuario Asociado:

Requistitos de Usuario asociados:
1. (Link RU)
- [ ] Initialization
- [ ] Concept Location
- [ ] Impact Analysis
- [ ] Prefactoring
- [ ] Change Propagation
- [ ] Verification
- [ ] Postfactoring
- [ ] Conclusion

**Comment by belisariops** [comment]
Se decidio no realizar este requisito, debido a que no complementa ni un RU.
