### ISSUE TITLE
RS 019: Efectos de sonido

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#34]
- Descripción: Agregar efectos de sonido a los saltos y ataques del personaje, estos de deben implementar con el engine utilizado EDX.
- Fuente:
- Prioridad: Critica.
- Estabilidad:
- Fecha Actualización: 27/10/2016
- Estado: No cumple.
- Incremento: 
- Tipo: Restricción.
- Usuario Asociado: Cliente de la aplicación.

Requistitos de Usuario asociados:
1. [RU 009: Efectos de sonido](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-009-efectos-de-sonido)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by CristobalVelasquezV** [comment]
**Initialization:** 
La música se ejecuta directamente en cada etapa y no existen efectos de sonido para ninguna acción del personaje.

**Comment by CristobalVelasquezV** [comment]
**Concept Location:**
 Se debe implementar una clase encargada de la música y efectos de sonido que pueda almacenar una canción por etapa, los efectos de salto y ataques del personaje. La música se activara en la clase de cada etapa en cambio los efectos de sonido se activaran en la clase Hero que es la encargada de controlar los movimientos del personaje.

**Comment by CristobalVelasquezV** [comment]
**Impact Analysis**

Clases afectadas:

1. Game Screen
2. Map Screen
3. MenuScreen
4. PokeCenterScreen
5. PokeComputerScreen
6. ShopScreen
7. SimpleScreen
8. Hero
9. Enemy
10. GameStage
1. Game Screen
2. Map Screen
3. MenuScreen
4. PokeCenterScreen
5. PokeComputerScreen
6. ShopScreen
7. SimpleScreen
8. Hero
9. Enemy
10. GameStage

**Comment by CristobalVelasquezV** [comment]
**Prefactoring**
Se agrego el packete audio que se encarga de aplicar los sonidos en el juego, son 3 clases gdxSoundeffenemy,gdxSoundeffhero y gdxSoundeffplayer se encargan de los sonidos asociados al enemigo, al heroe y a las musicas del juego.

**Comment by CristobalVelasquezV** [comment]
**Change Propagation**
Se modicaron las clases:

1. Game Screen
2. Map Screen
3. MenuScreen
4. PokeCenterScreen
5. PokeComputerScreen
6. ShopScreen
7. SimpleScreen
8. Hero
9. Enemy
10. GameStage
1. Game Screen
2. Map Screen
3. MenuScreen
4. PokeCenterScreen
5. PokeComputerScreen
6. ShopScreen
7. SimpleScreen
8. Hero
9. Enemy
10. GameStage
11. Packete items

**Comment by CristobalVelasquezV** [comment]
**Verification**
Se termino de agregar efectos de sonido a los menus en la parte del codigo.

**Comment by CristobalVelasquezV** [comment]
**Postfactoring**
No requiere postfactoring hasta el momento.

**Comment by CristobalVelasquezV** [comment]
**Conclusion**
Efectos de sonido implementados con GDX.
