### ISSUE TITLE
RS 020: Agua

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#36]
- Descripcion: Se debe agregar agua a las etapas como plataformas
- Fuente: Cliente
- Prioridad: Crítica
- Estabilidad: Intransable
- Fecha Actualizacion: 26/10/2016
- Estado: cumple
- Incremento: 1
- Tipo: Funcional
- Usuario Asociado: 

Requistitos de Usuario asociados:
1. [RU 006: Crear agua](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-006-crear-agua)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by paolocurotto** [comment]
Agregado plataformas atravesables de color celeste que representan el agua, el juego solo detecta cuando entra y sale

**Comment by paolocurotto** [comment]
El agua es creable de igual forma que las plataformas, se cambió la textura
