### ISSUE TITLE
RS 021: Comportamiento Hero en agua

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#37]
- Descripcion: Se debe agregar comportamiento hero en agua, el hero debe poder nadar en las plataformas de agua
- Fuente: Cliente
- Prioridad: Crítica
- Estabilidad: Intransable
- Fecha Actualizacion: 10/11/2016
- Estado: cumple
- Incremento: 1
- Tipo: Funcional
- Usuario Asociado: 

Requistitos de Usuario asociados:
1. [RU 006: Crear agua](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-006-crear-agua)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by paolocurotto** [comment]
Initialization, Concept location, Impact analysis: Las clases a modificar deberían ser principalmente la de plataformas del agua y hero, el agua detecta al hero y le cambia su forma de movimiento

**Comment by paolocurotto** [comment]
Agregado funcionalidad de las plataformas,  existen pequeños bugs

**Comment by paolocurotto** [comment]
- Agregado animación al agua, la textura del agua esta compuesta por 32 imagenes para darle la animación. 

- Arreglado bug al tener 2 o más bloques de agua juntos

- Agregado interacción del agua para enemigos

**Comment by paolocurotto** [comment]
Bugs por arreglar:

- Al salir del agua, si el hero está tocando todo el tiempo una plataforma este hace un salto corto en vez de un salto normal. Arreglado, al final no era un bug

- Al salir del agua, el hero puede pasar demasiado tiempo en el aire aun con la posibilidad de hacer un salto normal, debería pasar que el hero al salir del agua no se aleje de la superficie y ahi haga el salto normal como si estuviera impulsandose con el agua y no con el aire, aunque igual es como raro pero asi debería ser. Se arregló aumentando la gravedad al salir del agua antes de realizar el primer salto

- Cuando el hero va caminando y se para entre una plataforma caminable y el agua (como si tuviera un pie en la tierra y el otro en el agua para lo cual las plataformas tienen que estar al mismo nivel) el juego detecta que el hero entró al agua, debería detectarse el ingreso cuando ya no está tocando la plataforma caminable
