### ISSUE TITLE
RS 022: Saves corruptos

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#38]
- Descripción: No se deben cargar archivos .sav corruptos que hacen que el juego lanze un null pointer exception
- Fuente: Joaquin Torres.
- Prioridad: Crítica.
- Estabilidad: Intransable.
- Fecha Actualización: 10/19/2016 19:21:00.
- Incremento: 0.
- Tipo: Calidad.
- Tipo de usuario asociado: Usuario de la aplicación.

Requistitos de Usuario asociados:
1. [RU 011: Mejorar Sistema de Guardado BFG](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-011-mejorar-sistema-de-guardado-bfg)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by gsanhueza** [comment]
**Initialization**

Comprobar que los SAV no estén corruptos.

**Comment by gsanhueza** [comment]
**Concept Location**

SAV, load, parse

**Comment by gsanhueza** [comment]
**Impact Analysis**

Clases que se podrían ver afectadas:
- SaveManager
- Hero
- LoadActor
- LevelReader
- GameText
- InputController
- PokeCenterScreen
- ShopScreen

**Comment by gsanhueza** [comment]
**Prefactoring**

Se agregaron métodos de manipulación para el estado corruptSAV. Se creó nuevo stage llamado CorruptSAVStage. Se hizo una bifurcación en MenuScreen para llevar a CorruptSAVStage si correspondía. Se modificó SaveManager para detectar el error en la carga del archivo JSON.

**Comment by gsanhueza** [comment]
**Change Propagation**

Se modificaron solo las clases:
- SaveManager
- MenuScreen
- MenuStage

**Comment by gsanhueza** [comment]
**Verification**

Se probó con SAVs antiguos y corrompiendo manualmente los nuevos, se muestra correctamente la pantalla de error.

**Comment by gsanhueza** [comment]
**Postfactoring**

Hasta el momento no requiere post-factoring.

**Comment by gsanhueza** [comment]
**Conclusion**

Se agregó detección y aviso de SAVs corruptos.
