### ISSUE TITLE
RS 024: Pantalla mini juegos 

### ISSUE THREAD

**Issue by belisariops** [belisariops/ATK#40]
- Descripción: En vez de que el botón minigame empiece un nuevo mini juego, se abrirá un menú donde estará el actual minigame y el nuevo modo survival.
- Fuente:
- Prioridad: Critica.
- Estabilidad: Intransable.
- Fecha Actualización:
- Estado: Cumple.
- Incremento: 1.
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicación.

Requistitos de Usuario asociados:
1. [RU 008: Modo survival](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-008-modo-survival)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by alvaroleons** [comment]
**Initialization**

Nuevo menu, en donde el usuario puede seleccionar entre el mini-juego ya implementado "Pikachu Runner", y el nuevo modo Survival.

**Comment by alvaroleons** [comment]
**Concept Location**

Stage, Screen.

**Comment by alvaroleons** [comment]
**Impact analysis**
- MenuScreen
- SimpleScreen
- AbstractStage

**Comment by alvaroleons** [comment]
**Prefactoring**

En MenuStage está el botón de acceso a Minigame, el cual nos lleva directamente al actual mini-juego "Pikachu Runner", por lo cual se crea un stage MiniGameStage, el cual contiene botones para seleccionar entre los dos mini-juegos.

**Comment by alvaroleons** [comment]
**Change Propagation**

La clase MenuScreen fue impactada.

**Comment by alvaroleons** [comment]
**Verification**

Funciona la implementación, el menú tiene la apariencia del menú principal, y los 3 botones visibles, para los 2 minigames y volver al menú, cumplen su función adecuadamente, sin memory leaks. Debería realizarse un cambio mínimo para cuando el modo Survival este implementado y que el botón correspondiente redireccione a este, el lugar en el código donde este cambio debe realizarse esta comentado.

**Comment by alvaroleons** [comment]
**Conclusion**

La implementación esta terminada, no debería ser necesario ningún cambio excepto por el botón al modo Survival que no hace nada.
