### ISSUE TITLE
RS 025: Cooldown para habilidades

### ISSUE THREAD

**Issue by Afromatico** [belisariops/ATK#49]
Se requiere implementar un sistema de cooldown para las habilidades.
- Descripcion: Los ataques de los pokemon necesitan un tiempo de espera para poder ser utilizados.
- Fuente: Juaquin Torres, Sergio.
- Prioridad: Critica.
- Estabilidad: Intransable.
- Fecha Actualizacion: 11/08/2016 15:27:00.
- Incremento: 0.
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicación.

Requisitos de Usuario asociados:
1.  [RU 014: Agregar cooldown a los ataques](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-014-agregar-cooldown-a-los-ataques)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by gsanhueza** [comment]
**Initialization**

Implementar cooldown de ataques.

**Comment by gsanhueza** [comment]
**Concept Location**

Cooldown, Attack, Hero, Magic, Key Press

**Comment by gsanhueza** [comment]
**Impact Analysis**

Clases que se podrían ver afectadas:
- Hero
- Attacks
- SpriteState
- Todos los states/*State
- GameActor

**Comment by gsanhueza** [comment]
**Prefactoring**

Se modificó el método _attackPrimary_ para detectar cooldown correspondiente. Se agregó una variable cooldown en SpriteState con un valor _default_. Se agregó getter de SpriteState en Attacks. Se implementó un par de valores distintos de cooldown en AcidState y BranchAttackState para probar cooldown flexible.

**Comment by gsanhueza** [comment]
**Change Propagation**

Se modificaron las clases:
- Hero
- Attacks
- AcidState
- BranchAttackState
- SpriteState

**Comment by gsanhueza** [comment]
**Verification**

Se probó con pokemon al azar para el valor por defecto (500 ms) y con los que usaban ataques de ácido y de rama (100 y 150 ms, respectivamente.)

**Comment by gsanhueza** [comment]
**Postfactoring**

Solo se requerirá cuando cada ataque necesite distintos cooldown.

**Comment by gsanhueza** [comment]
**Conclusion**

Se implementó cooldowns para los ataques.
