### ISSUE TITLE
RS 026 Cambiar magia utilizada por ataques

### ISSUE THREAD

**Issue by Afromatico** [belisariops/ATK#50]
- Descripcion: Los ataques de los pokemon utilizan cantidad variable de Magic.
- Fuente: Joaquín Torres, Sergio.
- Prioridad: Critica.
- Estabilidad: Intransable.
- Fecha Actualizacion: 06/12/2016
- Estado: Cumple.
- Incremento: 2.
- Tipo: Funcional.
- Usuario Asociado: Usuario de la aplicación.

Requisitos de Usuario asociados:
[ RU002: Agrega nuevos ataques y personajes](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-002-nuevos-ataques-y-personajes)

- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by martinpanza** [comment]
### Inicialization

Cambiar uso de magia por ataque.

**Comment by martinpanza** [comment]
### Concept Location

-Magic
-Attack

**Comment by martinpanza** [comment]
### Impact Analysis

Clases que podrían verse afectadas:

-Todas las clases de los paquetes attacks y attacks.states
-Friend y sus subclases
-Boss
-Hero
-Enemy
-Attacks
-LeppaBerry

**Comment by martinpanza** [comment]
### Prefactoring

En el método attackPrimary de la clase Hero, se llama a la clase Friend mediante un nuevo método getAttackMagicRequirement para obtener el valor que se debe restar a la magia de Hero. Cada subclase de Friend llama, a su vez, a una variable estática del ataque correspondiente con el valor a restar.

**Comment by martinpanza** [comment]
### Change Propagation

Clases impactadas:
-Hero
-Friend y sus subclases
-SpriteState y sus subclases

**Comment by martinpanza** [comment]
### Verification

Se testeó con valores extremos en que Hero no perdía magia, y por otro lado, el caso en que el pokemon perdía toda la magia. Luego se utilizaron y testearon los valores que corresponden.

**Comment by martinpanza** [comment]
### Postfactoring

Se utiliza un método getter para establecer privacidad.
Podrían cambiarse los valores de acuerdo a los requerimientos del juego.

**Comment by martinpanza** [comment]
### Conclusion

Cada ataque utiliza una cantidad de magia determinada
