### ISSUE TITLE
RS 027 Refactorizar Tipos de pokemon, implementarlos como Singleton

### ISSUE THREAD

**Issue by Afromatico** [belisariops/ATK#56]
- Descripción: Hay que cambiar la forma en que se implementaron los Tipos, hay que transformarlos en singleton para que no se sobrecargue de objetos.
- Fuente: Américo Ferrada.
- Prioridad: Deseable.
- Estabilidad: Transable.
- Fecha Actualizacion: 23/11/2016
- Estado: Cumple.
- Incremento: 2.
- Tipo: Calidad.
- Usuario Asociado: Usuario de la aplicación.

Requisitos de Usuario asociados:
[ RS 001: Tipo de pokemon](https://github.com/belisariops/ATK/issues/15)

- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by martinpanza** [comment]
### Inicialization

Implementar Singleton en Tipos de Pokemon.

**Comment by martinpanza** [comment]
### Concept Location

-Type
-Pokemon

**Comment by martinpanza** [comment]
### Impact Analysis

Clases que podrían verse afectadas

-AbstractType y sus subclases
-Hero
-Enemy
-Formulas
-AbstractFriend y sus subclases
-SpriteState y sus subclases
-Attacks y sus subclases

**Comment by martinpanza** [comment]
### Prefactoring

En todas las subclases de AbstractType se utiliza constructor privado junto con un metodo getInstance estático para implementar singleton. Tanto ataques como Friends deben utilizar este método a partir de ahora.

**Comment by martinpanza** [comment]
### Change Propagation

Clases que fueron impactadas:

-AbstractFriend y subclases
-SpriteState y subclases

**Comment by martinpanza** [comment]
### Verification

Se confirma el funcionamiento normal de la aplicación.

**Comment by martinpanza** [comment]
### Postfactoring

Se propone utilización de Flyweight en vez de Singleton @Afromatico @belisariops 
Se crea nuevo issue con la refactorización propuesta.

**Comment by martinpanza** [comment]
### Conclusion

Pokemon Types usan Singleton.
