### ISSUE TITLE
RS 037 Imagenes de Pokemon en PC

### ISSUE THREAD

**Issue by Benrodf** [belisariops/ATK#59]
- Descripcion: En caso de existir Pokemon con los atributos de vida alterados ( es decir, no en su maximo) y se hace un Swap con otro Pokemon, las imagenes quedan superpuestas, afectando el resultado final. Esto se debe a que cada vez que se realiza un Swap se dibujan todas las imagenes del arreglo de Pokemon encima de las anteriores, en lugar de hacer un "refresh" de la pantalla. Sin embargo, el intercambio de Pokemon si se realiza correctamente.
- Fuente: Benjamín Rodríguez.
- Prioridad: Critica
- Estabilidad: Intransable
- Fecha Actualizacion: 23/11/2016
- Estado: Cumple.
- Incremento: 1.
- Tipo: Calidad.
- Usuario Asociado: Usuario de la aplicacion.

Requistitos de Software asociados:
1. [RS 029: Actualizar pantalla de PC luego del Intercambio](https://github.com/belisariops/ATK/issues/60)
2. [RS 030: Mejorar la vista de elementos intercambiados en PC](https://github.com/belisariops/ATK/issues/61)

- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by martinpanza** [comment]
### Inicialization

Arreglar actualización de imágenes de Swap en PokeComputer.

**Comment by martinpanza** [comment]
### Concept Location

Update, Swap, PokeComputer

**Comment by martinpanza** [comment]
### Impact Analysis

-AbstractFriend
-PokeComputerScreen
-Hero
-Enemy

**Comment by martinpanza** [comment]
### Prefactoring

Se altera el método swapPokemon. En vez de volver a mostrar las imagenes de todos los pokemones, se guardan en un arreglo detro de la clase para cambiar los indices y las posiciones en pantalla de las imágenes cada vez que se haga swap. Se dibujan llamando a stage.addActor(actor) el cual no agrega actores nuevos si ya tiene incorporado al actor que recibe por lo que solo lo actualiza.

**Comment by martinpanza** [comment]
### Change Propagation

Solo se realizaron cambios en la clase PokeComputerScreen

**Comment by martinpanza** [comment]
### Verification

Se testea para pokemones con todas sus estadísticas llenas (vida y magia), pokemones con estadísticas no completas y pokemones con estadísticas vacías.

**Comment by martinpanza** [comment]
### Verification

Se confirma funcionamiento y se mantiene encapsulation

**Comment by martinpanza** [comment]
### Conclusion

Se soluciona el bug
