### ISSUE TITLE
RS 029: Actualizar pantalla de PC luego del Intercambio

### ISSUE THREAD

**Issue by Benrodf** [belisariops/ATK#60]
- Descripción: Se requiere implementar una forma de actualizar la pantalla, sin la necesidad de dibujar la imagenes de los Pokemon encima de las anteriores, de forma que se refresquen todas las imagenes y se borren las anteriores. Actualmente esto genera un bug que altera las imagenes en caso de no tener los atributos de vida en su maximo a la hora del intercambio.
- Fuente: Benjamín Rodríguez.
- Prioridad: Deseado.
- Estabilidad: Transable.
- Fecha Actualizacion: 23/11/2016
- Estado: Cumple.
- Incremento: 1.
- Tipo: Calidad.
- Usuario Asociado: Usuario de la aplicación.

Requisitos de Usuario asociados:
1. [RU 003: Crear almacenamiento personajes](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-003-crear-almacenamiento-personajes)

- [ ] Initialization
- [ ] Concept Location
- [ ] Impact Analysis
- [ ] Prefactoring
- [ ] Change Propagation
- [ ] Verification
- [ ] Postfactoring
- [ ] Conclusion

**Comment by martinpanza** [comment]
Lo arreglé por casualidad al hacer #59
