### ISSUE TITLE
RS 032: Memory Leak en la pantalla "Load files"

### ISSUE THREAD

**Issue by Benrodf** [belisariops/ATK#68]
- Descripción: En la pantalla "Load files", donde se elige cual archivo se quiere cargar, si uno se queda el suficiente tiempo ocurre un memory leak que hace colapsar el juego. 
- Fuente: Benjamín Rodríguez.
- Prioridad:   .
- Estabilidad:  .
- Fecha Actualizacion: 
- Estado: .
- Incremento: .
- Tipo: Calidad.
- Usuario Asociado: Usuario de la aplicación.

Requisitos de Usuario asociados:

- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by alvaroleons** [comment]
**Initialization:**

Encontrar y detener el creciente uso de memoria en la pantalla "Load Files".

**Comment by alvaroleons** [comment]
**Concept Location:**

Screen, Stage, Actors.

**Comment by alvaroleons** [comment]
**Impact Analysis:**

- LoadStage
- LoadActor

**Comment by alvaroleons** [comment]
**Prefactoring:**

La escena LoadStage es renderizada constantemente, y la memoria se llenava sin que exista necesariamente un cambio en la pantalla.
Esto era causado por la forma de instanciar los pokemon para cargar los iconos correspondientes a sus caras, que se hacia cada cuadro por segundo. Se descubrió como causante un método para dibujar en la pantalla, dentro de la clase LoadActor y se corrigió tal que se instanciaran las imágenes solo una vez.

**Comment by alvaroleons** [comment]
**Change Propagation**

Solo la clase LoadActor fue impactada.

**Comment by alvaroleons** [comment]
**Verification**

Funciona la implementación, la memoria se estabilizo sin afectar la funcionalidad de la pantalla "Load Files" .

**Comment by alvaroleons** [comment]
**Conclusion**

La implementación esta terminada, no debería ser necesario ningún cambio ya que la funcionalidad de la pantalla, y sin problemas de memoria, esto para todos los computadores de quienes estamos trabajando en el proyecto.
