### ISSUE TITLE
RS 035 Arreglar el ataque de tipo hielo. 

### ISSUE THREAD

**Issue by jaevespinoza** [belisariops/ATK#81]
Descripción: Para algunos pokemon, el ataque de hielo colisiona con el piso (Snover por ejemplo). Es necesario arreglar esto para tener una mejor experiencia en el juego y no tener que estar saltando para atacar.
Fuente: Javier Espinoza
Fecha Actualizacion: 22/11/2016
Usuario Asociado: Usuario de la aplicación.

**Comment by Afromatico** [comment]
Lo solucioné agregando 0.3 a la altura inicial.
