### ISSUE TITLE
RS 036 Solucionar error al hacer swap en PC

### ISSUE THREAD

**Issue by martinpanza** [belisariops/ATK#84]
- Descripción: En la pantalla de PokeComputer ocurre un error al hacer swap si no se tiene un Pokemon en backup. Se debe manejar el error de alguna manera.
- Fuente: Martín Panza.
- Prioridad: Deseable.
- Estabilidad: Transable.
- Fecha Actualizacion: 24/11/2016
- Estado: No cumple.
- Incremento: 0.
- Tipo: Calidad.
- Usuario Asociado: Usuario de la aplicación.

- [ ] Initialization
- [ ] Concept Location
- [ ] Impact Analysis
- [ ] Prefactoring
- [ ] Change Propagation
- [ ] Verification
- [ ] Postfactoring
- [ ] Conclusion

**Comment by Benrodf** [comment]
Solucionado. (mas adelante completo esto)
