### ISSUE TITLE
RS 039: Visualización de caracteristicas de Pokemon seleccionado en PC

### ISSUE THREAD

**Issue by Benrodf** [belisariops/ATK#98]
- Descripcion: Mejorar la calidad de la interfaz de usuario en el PokeComputer (PC) implementando una vista de las caracteristicas del Pokemon previamente seleccionado con el indice, tales como el nombre, nivel, experiencia acumulada, tipo y todo lo que se considere necesario saber a la hora elegir racionalmente un intercambio, generando un sistema mas intuitivo para el usuario.
- Fuente: Joaquin Torres, Sergio Peñafiel.
- Prioridad: Critica
- Estabilidad: Intransable
- Fecha Actualizacion: 04/12/2016
- Estado: Cumple.
- Incremento: 1
- Tipo: Calidad.
- Usuario Asociado: Usuario de la aplicacion.

Requistitos asociados:
1. [RU 003: Crear almacenamiento personajes](https://github.com/belisariops/ATK/wiki/Requisitos-de-Usuario#ru-003-crear-almacenamiento-personajes)
2. [RS 009: PC](https://github.com/belisariops/ATK/issues/23)
- [x] Initialization
- [x] Concept Location
- [x] Impact Analysis
- [x] Prefactoring
- [x] Change Propagation
- [x] Verification
- [x] Postfactoring
- [x] Conclusion

**Comment by alvaroleons** [comment]
**Initialization**

Nuevos actor en PokeComputer, en donde el usuario puede observar las distintas características de sus pokemon para elegir su equipo.

**Comment by alvaroleons** [comment]
**Concept Location**

Screen, Actors.ui

**Comment by alvaroleons** [comment]
**Impact analysis**

- PokeComputerScreen
- SimpleScreen
- Actor

**Comment by alvaroleons** [comment]
**Prefactoring**

Se crea un actor llamado FriendInfo, el cual corresponde a un cuadro con la información relevante de un pokemon, que se puede actualizar cuando se desee.
Se agregaron dos de estos actores al PokeComputerScreen, uno correspondiente al equipo y el otro al backup, y se actualiza cada vez que un indice de selección cambia.

**Comment by alvaroleons** [comment]
**Change Propagation**

La clase PokeComputerScreen fue impactada.

**Comment by alvaroleons** [comment]
**Verification**

Funciona la implementación, la interfaz tiene mejor apariencia, se probaron distintas posibles combinaciones de selección de pokemon y se cambio para que sea mas amigable con el usuario, y libre de bugs.

**Comment by alvaroleons** [comment]
**Conclusion**

La implementación esta terminada, interfaz del PokeComputer es mucho mas amigable con el usuario y no debería ser necesario ningún cambio.
